### ISSUE TITLE
0600 - Insert empresa

### ISSUE THREAD

**Issue by xvatxx** [proj-padaria/padaria-doc#6]
Foram adicionadas três empresas quando deveria ser adicionada somente a empresa do seu Joaquim.
Falta inserir os dias de plano de pagamento.

**Comment by gitmeira** [comment]
Ajustado insert de empresa e inserido valores no plano de pagamento dias.

**Comment by gitmeira** [comment]
Alterado nome da ddl de 0600 para 0011
